import test from 'node:test';
import assert from 'node:assert/strict';
import ts from 'typescript';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {indexedDB} from 'fake-indexeddb';
import {noteSchema,baseRecord} from '../lib/focusbase/domain.ts';
await mkdir(new URL('../outputs/',import.meta.url),{recursive:true});
const transpile=async name=>ts.transpileModule(await readFile(new URL(`../lib/focusbase/${name}.ts`,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace("from './domain'","from '../lib/focusbase/domain.ts'").replace("from './task-expiry'","from './cloud-expiry-runtime.mjs'");
await writeFile(new URL('../outputs/cloud-expiry-runtime.mjs',import.meta.url),await transpile('task-expiry'));
await writeFile(new URL('../outputs/cloud-store-runtime.mjs',import.meta.url),await transpile('store'));
Object.assign(globalThis,{indexedDB});
const store=await import('../outputs/cloud-store-runtime.mjs');
function backend(ownerId){let state=null;return {ownerId,load:async()=>state&&structuredClone(state),save:async(next,expected)=>{if((state?.revision||0)!==expected)throw Object.assign(Error('Conflict'),{name:'WorkspaceConflict'});state=structuredClone(next);return structuredClone(state)},peek:()=>state}}
const defer=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve}};
test('cloud workspace isolation and failure behavior',async()=>{
  await store.configureWorkspace(null);
  await store.mutate(s=>s.notes.push(noteSchema.parse(baseRecord('Local original'))));
  const local=await store.readLocalWorkspace();
  const a=backend('A'),b=backend('B');
  await store.configureWorkspace(a);
  const ticketA=store.getWorkspaceGeneration();
  await Promise.all(Array.from({length:5},(_,i)=>store.mutate(s=>s.notes.push(noteSchema.parse(baseRecord('A'+i))))));
  assert.equal(a.peek().notes.length,5);assert.equal(a.peek().revision,5);
  await store.configureWorkspace(b);
  await assert.rejects(store.mutate(s=>s.notes.push(noteSchema.parse(baseRecord('stale component'))),{generation:ticketA}),/Аккаунт изменился/);
  const bs=await store.mutate(()=>{});assert.equal(bs.notes.length,0);
  assert.deepEqual(await store.readLocalWorkspace(),local);
  const wait=defer();const entered=defer();
  const delayed={...a,save:async(...args)=>{entered.resolve();await wait.promise;return a.save(...args)}};
  await store.configureWorkspace(delayed);
  const inFlight=store.mutate(s=>s.notes.push(noteSchema.parse(baseRecord('A in flight'))));
  await entered.promise;
  await store.configureWorkspace(b);wait.resolve();
  await assert.rejects(inFlight,/Аккаунт изменился/);
  assert.equal((await store.mutate(()=>{})).notes.length,0);
  const failed={...b,save:async()=>{throw Error('Offline')}};
  await store.configureWorkspace(failed);
  await assert.rejects(store.mutate(s=>s.notes.push(noteSchema.parse(baseRecord('lost')))),/Offline/);
  assert.equal(b.peek().notes.length,0);
  await store.configureWorkspace(a);
  const external={...a.peek(),revision:a.peek().revision+1,settings:{...a.peek().settings,customQuote:'Other device'}};
  await a.save(external,a.peek().revision);
  await assert.rejects(store.mutate(s=>s.settings.customQuote='Overwrite'),{name:'WorkspaceConflict'});
  assert.equal((await store.mutate(()=>{})).settings.customQuote,'Other device');
  const loading=defer();const loadA=store.configureWorkspace({...a,load:()=>loading.promise});
  await store.configureWorkspace(b);loading.resolve(a.peek());await loadA;
  assert.equal((await store.mutate(()=>{})).notes.length,0);
  store.suspendWorkspace();await assert.rejects(store.mutate(()=>{}),/Аккаунт изменился/);
  await store.configureWorkspace(null);assert.deepEqual(await store.readLocalWorkspace(),local);
});
