import { z } from 'zod';
const text=z.string().max(100000), title=z.string().min(1).max(500), id=z.string().min(1).max(200), day=z.string().regex(/^$|^\d{4}-\d{2}-\d{2}$/);
const base={id,title:z.string().min(1).max(500),createdAt:z.number(),updatedAt:z.number(),deletedAt:z.number().nullable().default(null),archived:z.boolean().default(false),demo:z.boolean().default(false)};
export const directions=['Английский / IELTS','Математика / SAT','Школа','Программирование','Поступление','Личное','UNT / ҰБТ'] as const;
export const examIds=['ielts','sat','unt'] as const;
export type ExamId=typeof examIds[number];
const examFields={examId:z.enum(['',...examIds]).default(''),examSection:z.string().max(100).default('')};
const validDate=(value:string)=>!!value&&Number.isFinite(Date.parse(value+'T12:00:00Z'))&&new Date(value+'T12:00:00Z').toISOString().slice(0,10)===value;
const calendarDate=z.string().refine(validDate,'Выберите корректную дату');
export const examGoalSchema=z.object({...base,examId:z.enum(examIds),target:z.string().max(120).default(''),date:calendarDate,completed:z.boolean().default(false)});
export const calendarEventSchema=z.object({...base,date:calendarDate,time:z.string().regex(/^$|^([01]\d|2[0-3]):[0-5]\d$/).default(''),description:z.string().max(2000).default(''),examId:z.enum(['',...examIds]).default('')});
export type ExamGoal=z.infer<typeof examGoalSchema>;
export type CalendarEvent=z.infer<typeof calendarEventSchema>;
export const statuses={inbox:'Входящие',todo:'К выполнению',progress:'В работе',done:'Готово',cancelled:'Отменена',archive:'Архив'};
export const taskSchema=z.object({...base,...examFields,completedAt:z.number().finite().nonnegative().nullable().default(null),description:text.default(''),direction:text.default(directions[0]),projectId:z.string().default(''),status:z.enum(['inbox','todo','progress','done','cancelled','archive']).default('inbox'),priority:z.enum(['A','B','C']).default('B'),date:day.default(''),deadline:day.default(''),minutes:z.number().int().min(1).max(1440).default(25),checklist:z.array(z.object({id,text,done:z.boolean()})).default([]),resourceIds:z.array(id).default([]),tags:z.array(text).default([]),repeat:z.enum(['none','daily','weekly']).default('none'),nextId:z.string().default(''),time:text.default(''),anchor:text.default('')});
export const resourceSchema=z.object({...base,...examFields,review:z.object({due:calendarDate,step:z.number().int().min(0).max(4),lastReviewed:day.default('')}).nullable().default(null),url:z.string().max(5000).refine(v=>{try{return ['https:','http:'].includes(new URL(v).protocol)}catch{return false}},'Нужна ссылка http:// или https://'),type:z.enum(['Ссылка','Статья','Видео','Курс','Учебник','Документ','Инструмент']).default('Ссылка'),direction:text.default(directions[0]),tags:z.array(text).default([]),why:text.default(''),status:z.enum(['Сохранено','Изучаю','Изучено']).default('Сохранено'),favorite:z.boolean().default(false),collection:text.default(''),projectId:z.string().default('')});
export const noteSchema=z.object({...base,body:text.default(''),pinned:z.boolean().default(false),taskId:z.string().default(''),projectId:z.string().default(''),resourceId:z.string().default('')});
export const projectSchema=z.object({...base,description:text.default(''),direction:text.default(directions[3])});
export const columnTypes=['Текст','Число','Дата','Ссылка','Checkbox','Выбор','Мультивыбор','Сумма'] as const;
export const columnSchema=z.object({id,title:z.string().min(1).max(100),type:z.enum(columnTypes),options:z.array(text).default([]),currency:z.string().default('KZT'),pinned:z.boolean().default(false)});
const cell=z.union([z.string(),z.number().finite(),z.boolean(),z.array(z.string())]);
export const tableSchema=z.object({...base,columns:z.array(columnSchema).min(1).max(100),rows:z.array(z.object({id,cells:z.record(cell),deletedAt:z.number().nullable().default(null)})).max(50000)});
export const eventSchema=z.object({...base,weekday:z.number().int().min(0).max(6),start:z.string().regex(/^\d{2}:\d{2}$/),end:z.string().regex(/^\d{2}:\d{2}$/)});
export const activeSchema=z.object({id,taskId:z.string(),mode:z.enum(['free','countdown','pomodoro']),workMinutes:z.number().min(1).max(1440),breakMinutes:z.number().min(1).max(120),phase:z.enum(['work','break']),phaseMs:z.number().min(0),workMs:z.number().min(0),runSince:z.number().nullable(),startedAt:z.number(),cycles:z.number().int().min(0),thoughts:z.array(text)});
export const sessionSchema=z.object({...base,taskId:z.string(),startedAt:z.number(),endedAt:z.number(),workMs:z.number().min(0),summary:text,result:text,nextStep:text,thoughts:z.array(text)});
export const settingsSchema=z.object({timezone:z.string().refine(v=>{try{new Intl.DateTimeFormat('ru',{timeZone:v});return true}catch{return false}},'Неизвестный часовой пояс'),theme:z.enum(['light','dark']),dayMode:z.enum(['Minimum','Normal','Deep Work']),mainTaskId:z.string(),sound:z.boolean(),notifications:z.boolean(),customQuote:z.string().max(240).default(''),customQuoteJapanese:z.string().max(80).default('')});
export const stateSchema=z.object({version:z.literal(1),revision:z.number().int().min(0),settings:settingsSchema,tasks:z.array(taskSchema),resources:z.array(resourceSchema),notes:z.array(noteSchema),projects:z.array(projectSchema),tables:z.array(tableSchema),events:z.array(eventSchema),examGoals:z.array(examGoalSchema).default([]),calendarEvents:z.array(calendarEventSchema).default([]),sessions:z.array(sessionSchema),active:activeSchema.nullable(),weekTemplates:z.array(z.object({id,title,items:z.array(z.object({title,direction:text,weekday:z.number().min(0).max(6),minutes:z.number().min(1).max(1440),time:text,anchor:text}))})),appliedWeeks:z.array(z.string())});
export type Task=z.infer<typeof taskSchema>;export type Resource=z.infer<typeof resourceSchema>;export type Note=z.infer<typeof noteSchema>;export type Project=z.infer<typeof projectSchema>;export type DataTable=z.infer<typeof tableSchema>;export type Column=z.infer<typeof columnSchema>;export type Active=z.infer<typeof activeSchema>;export type State=z.infer<typeof stateSchema>;export type Session=z.infer<typeof sessionSchema>;
export type EntityKind='tasks'|'resources'|'notes'|'projects'|'tables'|'events'|'sessions'|'examGoals'|'calendarEvents';
export const kinds:EntityKind[]=['tasks','resources','notes','projects','tables','events','sessions','examGoals','calendarEvents'];
export const uid=()=>crypto.randomUUID();
export function baseRecord(title:string){return {id:uid(),title,createdAt:Date.now(),updatedAt:Date.now(),deletedAt:null,archived:false,demo:false}}
export const visible=(x:{deletedAt:number|null;archived:boolean})=>!x.deletedAt&&!x.archived;
export const openTask=(x:Task)=>visible(x)&&!['done','cancelled','archive'].includes(x.status);
export function localDay(timezone:string,at=Date.now()){return new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(at)}
export function addDays(day:string,n:number){const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
export function weekStart(day:string){const d=new Date(day+'T12:00:00Z');return addDays(day,-((d.getUTCDay()+6)%7))}
export function examFor(item:{examId?:string;direction?:string}):ExamId|''{if(item.examId&&examIds.includes(item.examId as ExamId))return item.examId as ExamId;return item.direction==='Английский / IELTS'?'ielts':item.direction==='Математика / SAT'?'sat':item.direction==='UNT / ҰБТ'?'unt':''}
export type CalendarItem={id:string;date:string;title:string;kind:'task'|'deadline'|'goal'|'event'|'routine';time:string;examId:ExamId|'';completed:boolean};
export function calendarItems(s:State,from:string,to:string):CalendarItem[]{
  const items:CalendarItem[]=[];
  const inside=(date:string)=>!!date&&date>=from&&date<=to;
  for(const t of s.tasks.filter(t=>visible(t)&&!['cancelled','archive'].includes(t.status))){
    if(inside(t.date)&&t.date!==t.deadline)items.push({id:t.id,date:t.date,title:t.title,kind:'task',time:t.time,examId:examFor(t),completed:t.status==='done'});
    if(inside(t.deadline))items.push({id:t.id,date:t.deadline,title:t.title,kind:'deadline',time:'',examId:examFor(t),completed:t.status==='done'});
  }
  for(const g of s.examGoals.filter(visible))if(inside(g.date))items.push({id:g.id,date:g.date,title:g.title,kind:'goal',time:'',examId:g.examId,completed:g.completed});
  for(const e of s.calendarEvents.filter(visible))if(inside(e.date))items.push({id:e.id,date:e.date,title:e.title,kind:'event',time:e.time,examId:e.examId,completed:false});
  for(let date=from;date<=to;date=addDays(date,1))for(const e of s.events.filter(e=>visible(e)&&e.weekday===(new Date(date+'T12:00:00Z').getUTCDay()+6)%7))items.push({id:e.id,date,title:e.title,kind:'routine',time:e.start,examId:'',completed:false});
  return items.sort((a,b)=>a.date.localeCompare(b.date)||Number(a.completed)-Number(b.completed)||a.time.localeCompare(b.time)||a.title.localeCompare(b.title));
}
export function emptyState():State{return {version:1,revision:0,settings:{timezone:'Asia/Qyzylorda',theme:'light',dayMode:'Normal',mainTaskId:'',sound:false,notifications:false,customQuote:'',customQuoteJapanese:''},tasks:[],resources:[],notes:[],projects:[],tables:[],events:[],examGoals:[],calendarEvents:[],sessions:[],active:null,weekTemplates:[],appliedWeeks:[]}}
export function completeTask(s:State,id:string,now=Date.now()){const t=s.tasks.find(t=>t.id===id);if(!t)throw Error('Задача не найдена');if(t.status==='done')return;t.status='done';t.completedAt=now;t.updatedAt=now;if(t.repeat!=='none'&&!t.nextId){const date=addDays(t.date||localDay(s.settings.timezone),t.repeat==='daily'?1:7);const nextId=uid();t.nextId=nextId;s.tasks.push({...structuredClone(t),...baseRecord(t.title),id:nextId,date,deadline:'',status:'todo',completedAt:null,nextId:'',checklist:t.checklist.map(c=>({...c,done:false}))})}}
export function setTaskStatus(s:State,id:string,status:Task['status'],now=Date.now()){if(status==='done'){completeTask(s,id,now);return}const t=s.tasks.find(t=>t.id===id);if(!t)throw Error('Задача не найдена');t.status=status;t.updatedAt=now;if(status!=='archive')t.completedAt=null}
export function canonicalUrl(url:string){const u=new URL(url);u.hash='';u.hostname=u.hostname.toLowerCase();u.searchParams.sort();return u.toString().replace(/\/$/,'')}
export function actualMs(s:State,taskId:string){return s.sessions.filter(x=>!x.deletedAt&&x.taskId===taskId).reduce((n,x)=>n+x.workMs,0)}
export function phaseLimit(a:Active){return a.mode==='free'?Infinity:(a.phase==='work'?a.workMinutes:a.breakMinutes)*60000}
export function elapsed(a:Active,now=Date.now()){return Math.min(phaseLimit(a),a.phaseMs+(a.runSince===null?0:Math.max(0,now-a.runSince)))}
export function worked(a:Active,now=Date.now()){return a.workMs+(a.phase==='work'?elapsed(a,now):0)}
export function pause(a:Active,now=Date.now()){a.phaseMs=elapsed(a,now);a.runSince=null}
export function startFocus(s:State,taskId:string,mode:Active['mode'],workMinutes:number,breakMinutes:number,now=Date.now()){if(s.active)throw Error('Уже есть активная сессия. Завершите её или продолжите.');if(taskId&&!s.tasks.some(t=>t.id===taskId&&openTask(t)))throw Error('Выберите доступную незавершённую задачу');s.active={id:uid(),taskId,mode,workMinutes,breakMinutes,phase:'work',phaseMs:0,workMs:0,runSince:now,startedAt:now,cycles:0,thoughts:[]};const t=s.tasks.find(t=>t.id===taskId);if(t)t.status='progress'}
export function nextPhase(s:State,now=Date.now()){const a=s.active;if(!a||a.mode!=='pomodoro')throw Error('Нет Pomodoro');if(elapsed(a,now)<phaseLimit(a))throw Error('Интервал ещё не завершён');if(a.phase==='work'){a.workMs+=elapsed(a,now);a.cycles++}a.phase=a.phase==='work'?'break':'work';a.phaseMs=0;a.runSince=now}
export function finishFocus(s:State,input:{summary:string;result:string;nextStep:string;done:boolean},now=Date.now()){const a=s.active;if(!a)throw Error('Сессия уже завершена');if(s.sessions.some(x=>x.id===a.id))throw Error('Сессия уже сохранена');s.sessions.push({...baseRecord(s.tasks.find(t=>t.id===a.taskId)?.title||'Свободный фокус'),id:a.id,taskId:a.taskId,startedAt:a.startedAt,endedAt:now,workMs:worked(a,now),summary:input.summary,result:input.result,nextStep:input.nextStep,thoughts:a.thoughts});if(input.done&&a.taskId)completeTask(s,a.taskId,now);s.active=null}
export function parseBackup(raw:string):State{const envelope=z.object({format:z.literal('focusbase-backup'),version:z.literal(1),exportedAt:z.string(),data:stateSchema}).parse(JSON.parse(raw));const s=envelope.data;const all=new Set<string>();for(const kind of kinds)for(const item of s[kind]){if(all.has(item.id))throw Error('Повторяющийся ID в резервной копии');all.add(item.id)};const has=(kind:EntityKind,v:string)=>!v||s[kind].some(x=>x.id===v);for(const t of s.tasks){if(!has('projects',t.projectId)||t.resourceIds.some(r=>!has('resources',r)))throw Error('Нарушены связи задачи')}for(const n of s.notes)if(!has('tasks',n.taskId)||!has('projects',n.projectId)||!has('resources',n.resourceId))throw Error('Нарушены связи заметки');for(const r of s.resources)if(!has('projects',r.projectId))throw Error('Нарушены связи материала');for(const session of s.sessions)if(!has('tasks',session.taskId))throw Error('Нарушены связи сессии');if(s.active&&!has('tasks',s.active.taskId))throw Error('Нарушены связи таймера');for(const t of s.tables){if(new Set(t.columns.map(c=>c.id)).size!==t.columns.length||new Set(t.rows.map(r=>r.id)).size!==t.rows.length)throw Error('Повторяющийся ID в таблице')};return s}
export function backup(s:State){const copy=structuredClone(s);if(copy.active)pause(copy.active);return JSON.stringify({format:'focusbase-backup',version:1,exportedAt:new Date().toISOString(),data:copy},null,2)}
export function csvEncode(rows:unknown[][]){return '\uFEFF'+rows.map(row=>row.map(v=>{const str=Array.isArray(v)?v.join('; '):String(v??'');const safe=/^[=+@\-\t\r]/.test(str)?"'"+str:str;return '"'+safe.replaceAll('"','""')+'"'}).join(',')).join('\r\n')}
export function csvParse(raw:string){const input=raw.replace(/^\uFEFF/,'');const rows:string[][]=[];let row:string[]=[],value='',quoted=false;for(let i=0;i<input.length;i++){const c=input[i];if(c==='"'){if(quoted&&input[i+1]==='"'){value+='"';i++}else if(quoted){quoted=false}else if(!value){quoted=true}else value+=c}else if(c===','&&!quoted){row.push(value);value=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&input[i+1]==='\n')i++;row.push(value);rows.push(row);row=[];value=''}else value+=c}if(quoted)throw Error('Незакрытая кавычка в CSV');if(value||row.length){row.push(value);rows.push(row)}return rows}
export const noteTemplates:Record<string,string>={'Конспект':'# Тема\n\n## Главное\n- \n\n## Пример\n\n## Вопросы\n- [ ] Проверить понимание','Разбор ошибки':'## Задание\n\nМой ответ: \nПравильный ответ: \n\n## Почему ошибся\n\n## Как проверить снова\n- [ ] Повторить без подсказки','План проекта':'## Цель\n\n## Результат\n\n## Шаги\n- [ ] Первый шаг','Итог недели':'## Что сделал\n\n## Что мешало\n\n## Что продолжить\n\n## Что убрать\n\n## Три задачи следующей недели\n1. \n2. \n3. ','Результат пробного теста':'## Тест и источник\n\nДата: \nУсловия: \nРезультат: / \n\n## Ошибки\n\n## Следующий шаг'};
export function tableTemplate(name:string):DataTable{const defs:Record<string,[string,Column['type']][]>={'Университеты':[['Университет','Текст'],['Страна','Текст'],['Программа','Текст'],['Дедлайн','Дата'],['Источник','Ссылка'],['Стоимость','Сумма'],['Учебный год','Текст'],['Проверено','Дата']],'Результаты пробников':[['Тест','Текст'],['Дата','Дата'],['Раздел','Текст'],['Результат','Число'],['Максимум','Число'],['Условия','Текст']],'Проекты и достижения':[['Название','Текст'],['Мой вклад','Текст'],['Результат','Текст'],['Подтверждение','Ссылка']],'Личный список ресурсов':[['Название','Текст'],['Ссылка','Ссылка'],['Изучено','Checkbox']]};return {...baseRecord(name),columns:(defs[name]||[['Название','Текст']]).map(([title,type],i)=>({id:uid(),title,type,options:[],currency:'KZT',pinned:i===0})),rows:[]}}
