import type {ExamId} from './domain';

export const exams:Record<ExamId,{name:string;subtitle:[string,string];direction:string;placeholder:string;sections:{id:string;label:[string,string]}[]}>= {
  ielts:{name:'IELTS',subtitle:['Английский для следующего шага.','English for your next step.'],direction:'Английский / IELTS',placeholder:'IELTS 7.5 — без разделов ниже 7.0',sections:[{id:'listening',label:['Listening','Listening']},{id:'reading',label:['Reading','Reading']},{id:'writing',label:['Writing','Writing']},{id:'speaking',label:['Speaking','Speaking']}]},
  sat:{name:'SAT',subtitle:['Reading & Writing. Math. Твой результат.','Reading & Writing. Math. Your result.'],direction:'Математика / SAT',placeholder:'SAT 1500+ к поступлению',sections:[{id:'reading-writing',label:['Reading & Writing','Reading & Writing']},{id:'math',label:['Math','Math']}]},
  unt:{name:'UNT · ҰБТ',subtitle:['Следующий шаг — твой университет.','Your university is the next step.'],direction:'UNT / ҰБТ',placeholder:'ҰБТ 120+ — подготовиться к гранту',sections:[{id:'history',label:['История Казахстана','Kazakhstan history']},{id:'math-literacy',label:['Математическая грамотность','Mathematical literacy']},{id:'reading-literacy',label:['Грамотность чтения','Reading literacy']},{id:'profile',label:['Профильные предметы','Profile subjects']}]}
};
export type StudyResource={id:string;examId:ExamId;section:string;title:string;description:[string,string];url:string;source:string;type:'Ссылка'|'Документ'|'Инструмент'|'Курс'};
// Verified against the exam providers on 2026-09-11. These are links, not copied question banks.
export const studyResources:StudyResource[]=[
 {id:'ielts-samples',examId:'ielts',section:'',title:'IELTS Academic · sample tests',description:['Официальные задания, ответы и аудио для трёх письменных разделов.','Official tasks, answer keys and audio for the written test sections.'],url:'https://ielts.org/take-a-test/preparation-resources/sample-test-questions/academic-test',source:'IELTS.org',type:'Документ'},
 {id:'ielts-listening',examId:'ielts',section:'listening',title:'Listening · practice',description:['Аудиозаписи, задания и транскрипты. Выбери Listening на странице.','Recordings, tasks and transcripts. Select Listening on the page.'],url:'https://ielts.org/take-a-test/preparation-resources/sample-test-questions/academic-test',source:'IELTS.org',type:'Документ'},
 {id:'ielts-reading',examId:'ielts',section:'reading',title:'Academic Reading · practice',description:['Тексты и типы вопросов с ключами для проверки. Выбери Academic Reading.','Texts and question types with answer keys. Select Academic Reading.'],url:'https://ielts.org/take-a-test/preparation-resources/sample-test-questions/academic-test',source:'IELTS.org',type:'Документ'},
 {id:'ielts-writing',examId:'ielts',section:'writing',title:'Academic Writing · practice',description:['Примеры заданий для письменной части. Выбери Academic Writing.','Sample writing tasks. Select Academic Writing.'],url:'https://ielts.org/take-a-test/preparation-resources/sample-test-questions/academic-test',source:'IELTS.org',type:'Документ'},
 {id:'ielts-speaking',examId:'ielts',section:'speaking',title:'Speaking · sample tasks',description:['Примеры заданий для устной части экзамена.','Sample tasks for the speaking test.'],url:'https://ielts.org/take-a-test/preparation-resources/sample-test-questions',source:'IELTS.org',type:'Ссылка'},
 {id:'sat-bluebook',examId:'sat',section:'',title:'Bluebook · full-length tests',description:['Полный пробник в приложении, в котором проходит цифровой SAT.','Full-length practice in the app used for the digital SAT.'],url:'https://satsuite.collegeboard.org/practice/practice-tests/bluebook',source:'College Board',type:'Инструмент'},
 {id:'sat-rw',examId:'sat',section:'reading-writing',title:'Reading & Writing · question bank',description:['Официальный банк заданий. Выбери Reading and Writing и нужный навык.','Official question bank. Select Reading and Writing and a skill to practice.'],url:'https://satsuite.collegeboard.org/practice/student-question-bank',source:'College Board',type:'Инструмент'},
 {id:'sat-math',examId:'sat',section:'math',title:'Math · question bank',description:['Задания по математике с фильтрами по навыкам и сложности.','Math questions with skill and difficulty filters.'],url:'https://satsuite.collegeboard.org/practice/student-question-bank',source:'College Board',type:'Инструмент'},
 {id:'unt-trial',examId:'unt',section:'',title:'ҰБТ · пробное тестирование',description:['Пробный тест на платформе Национального центра тестирования.','Practice test from the National Testing Center.'],url:'https://prob-ent.testcenter.kz/',source:'Ұлттық тестілеу орталығы',type:'Инструмент'},
 ...(['history','math-literacy','reading-literacy','profile'] as const).map((section,i)=>({id:'unt-'+section,examId:'unt' as const,section,title:['Қазақстан тарихы','Математикалық сауаттылық','Оқу сауаттылығы','Бейіндік пәндер'][i],description:['Темы, спецификации и примеры заданий. Выбери свой предмет на сайте НЦТ.','Topics, specifications and sample questions. Select your subject on the NTC website.'] as [string,string],url:'https://testcenter.kz/?page_id=23376',source:'Ұлттық тестілеу орталығы',type:'Документ' as const}))
];
