'use client';
import {useSyncExternalStore,useEffect} from 'react';
import {emptyState,stateSchema,State} from './domain';
let current:State|null=null;let error='';let dbPromise:Promise<IDBDatabase>|null=null;let channel:BroadcastChannel|null=null;const listeners=new Set<()=>void>();
const emit=()=>listeners.forEach(f=>f());
function database(){if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('focusbase',1);r.onupgradeneeded=()=>r.result.createObjectStore('workspace');r.onsuccess=()=>{r.result.onversionchange=()=>{r.result.close();dbPromise=null};resolve(r.result)};r.onerror=()=>{dbPromise=null;reject(r.error)};r.onblocked=()=>{error='Закройте другие вкладки FocusBase и обновите страницу.';emit()}});return dbPromise}
export async function reload(){try{const db=await database();const value=await new Promise<State|undefined>((resolve,reject)=>{const r=db.transaction('workspace','readonly').objectStore('workspace').get('personal');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});current=value?stateSchema.parse(value):emptyState();error='';emit()}catch(e){error='Не удалось открыть хранилище. '+String(e);emit()}}
export async function mutate(fn:(draft:State)=>void){try{const db=await database();const saved=await new Promise<State>((resolve,reject)=>{const tx=db.transaction('workspace','readwrite');const store=tx.objectStore('workspace');let next:State;let failure:unknown;const r=store.get('personal');r.onsuccess=()=>{try{next=stateSchema.parse(r.result||emptyState());fn(next);next.revision++;next=stateSchema.parse(next);store.put(next,'personal')}catch(e){failure=e;tx.abort()}};tx.oncomplete=()=>resolve(next);tx.onabort=()=>reject(failure||tx.error||new Error('Запись отменена'));tx.onerror=()=>reject(tx.error)});if(!current||saved.revision>=current.revision)current=saved;error='';emit();channel?.postMessage('changed');return saved}catch(e){error='Не удалось сохранить: '+(e instanceof Error?e.message:String(e));emit();throw e}}
function subscribe(f:()=>void){listeners.add(f);return()=>{listeners.delete(f)}}
let initialized=false;
export function useData(){const data=useSyncExternalStore(subscribe,()=>current,()=>null);const storageError=useSyncExternalStore(subscribe,()=>error,()=>'');useEffect(()=>{if(initialized)return;initialized=true;void reload();if(typeof BroadcastChannel!=='undefined'){channel=new BroadcastChannel('focusbase-changes');channel.onmessage=()=>void reload()}window.addEventListener('focus',()=>void reload())},[]);return {data,storageError}}
export function download(content:string,name:string,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
