'use client';
import {useState,useEffect,useCallback} from 'react';
import {Sun,CheckSquare,Timer,Library,NotebookPen,Table2,CalendarDays,Plus,Layers,Search,Settings,Focus,Archive,Trash2,WifiOff,AlertCircle} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {State,startFocus} from '@/lib/focusbase/domain';
import {useData,mutate,reload} from '@/lib/focusbase/store';
import {AppContext,Edit,Modal} from '@/components/focusbase/ui';
import {TaskForm,ResourceForm,NoteForm,ProjectForm} from '@/components/focusbase/forms';
import {TodayView,TasksView,ProjectsView,LibraryView,NotesView,SearchForm,QuickForm} from '@/components/focusbase/views';
import {FocusView,FinishForm} from '@/components/focusbase/focus';
import {TablesView,TableForm} from '@/components/focusbase/tables';
import {WeekView} from '@/components/focusbase/week';
import {SettingsView,ArchiveView} from '@/components/focusbase/settings';
const nav=[['Сегодня',Sun],['Задачи',CheckSquare],['Проекты',Layers],['Фокус',Timer],['Библиотека',Library],['Заметки',NotebookPen],['Мои таблицы',Table2],['План недели',CalendarDays]] as const;
function Navigation({view,go}:{view:string;go:(v:string)=>void}){const {setOpenMobile}=useSidebar();return <Sidebar className="app-sidebar"><SidebarHeader><div className="brand"><span className="brand-mark"><Focus size={22}/></span>FocusBase<span className="beta">beta</span></div><div className="workspace-label">ЛИЧНОЕ ПРОСТРАНСТВО</div></SidebarHeader><SidebarContent><SidebarMenu>{nav.map(([name,Icon])=><SidebarMenuItem key={name}><SidebarMenuButton isActive={view===name} onClick={()=>{go(name);setOpenMobile(false)}}><Icon/><span>{name}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="nav-divider"/><SidebarMenu>{([['Архив',Archive],['Корзина',Trash2]] as const).map(([name,Icon])=><SidebarMenuItem key={name}><SidebarMenuButton isActive={view===name} onClick={()=>{go(name);setOpenMobile(false)}}><Icon/><span>{name}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><div className="local-label">Данные на этом устройстве</div><SidebarMenuButton isActive={view==='Настройки'} onClick={()=>{go('Настройки');setOpenMobile(false)}}><Settings/>Настройки и данные</SidebarMenuButton><div className="profile"><span>Я</span><div>Моё пространство<small>Учёба · проекты · развитие</small></div></div></SidebarFooter></Sidebar>}
const viewSlugs:Record<string,string>={'Сегодня':'today','Задачи':'tasks','Проекты':'projects','Фокус':'focus','Библиотека':'library','Заметки':'notes','Мои таблицы':'tables','План недели':'week','Настройки':'settings','Архив':'archive','Корзина':'trash'};
export default function Home(){const {data:s,storageError}=useData();const [view,setView]=useState('Сегодня'),[editing,edit]=useState<Edit|null>(null),[toast,setToast]=useState(''),[online,setOnline]=useState(true);const go=useCallback((v:string)=>{setView(v);window.location.hash=viewSlugs[v]||'today'},[]);const run=useCallback(async(fn:(d:State)=>void,message?:string)=>{try{await mutate(fn);if(message)setToast(message);return true}catch(e){setToast(e instanceof Error?e.message:String(e));return false}},[]);const start=useCallback((taskId:string)=>{if(s?.active){go('Фокус');setToast('Продолжите текущую сессию или завершите её перед новой.');return}void run(d=>startFocus(d,taskId,'countdown',d.tasks.find(t=>t.id===taskId)?.minutes||25,5)).then(ok=>{if(ok)go('Фокус')})},[s?.active,go,run]);
useEffect(()=>{const hash=()=>{const found=Object.entries(viewSlugs).find(([,slug])=>'#'+slug===window.location.hash);if(found)setView(found[0])};hash();window.addEventListener('hashchange',hash);return()=>window.removeEventListener('hashchange',hash)},[]);
useEffect(()=>{document.documentElement.classList.toggle('dark',s?.settings.theme==='dark')},[s?.settings.theme]);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t)},[toast]);useEffect(()=>{const f=()=>setOnline(navigator.onLine);f();window.addEventListener('online',f);window.addEventListener('offline',f);return()=>{window.removeEventListener('online',f);window.removeEventListener('offline',f)}},[]);
useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();edit({kind:'search'})}if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='a'){e.preventDefault();edit({kind:'quick'})}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:'start_focusbase_task_creation',title:'Открыть создание задачи',description:'Opens the visible task form for user review; does not save or change the plan.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('Expected empty object');edit({kind:'tasks'});return {status:'form_opened'}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
if(!s)return <main className="loading-screen"><Focus size={35}/><h1>FocusBase</h1><p role="status">{storageError||'Открываем ваше пространство…'}</p>{storageError&&<button className="secondary" onClick={()=>void reload()}>Повторить</button>}</main>;
const titles:Record<string,string>={tasks:editing?.id?'Задача':'Новая задача',resources:editing?.id?'Материал':'Сохранить материал',notes:'Заметка',projects:editing?.id?'Проект':'Новый проект',tables:'Новая таблица',quick:'Быстрое добавление',search:'Поиск в пространстве',finish:'Итог фокус-сессии'};
return <AppContext.Provider value={{s,run,edit,go,start}}><SidebarProvider><Navigation view={view} go={go}/><SidebarInset><header className="topbar"><SidebarTrigger/><span className="breadcrumb">{view==='Настройки'?'Настройки и данные':view}</span><div className="top-actions"><button className="search-button" aria-label="Поиск в пространстве" onClick={()=>edit({kind:'search'})}><Search size={17}/><span>Поиск</span><kbd>Ctrl K</kbd></button><button className="primary" onClick={()=>edit({kind:'quick'})}><Plus size={17}/>Добавить</button></div></header>{!online&&<div className="offline-banner"><WifiOff size={16}/>Офлайн · изменения останутся на этом устройстве</div>}{storageError&&<div className="error-banner" role="alert"><AlertCircle size={18}/>{storageError}<button onClick={()=>void reload()}>Повторить чтение</button></div>}{s.active&&view!=='Фокус'&&<button className="active-banner" onClick={()=>go('Фокус')}><Timer size={16}/>{s.active.runSince===null?'Фокус на паузе':'Фокус запущен'} · {s.tasks.find(t=>t.id===s.active?.taskId)?.title||'Свободная сессия'}<span>Вернуться →</span></button>}<main className="page"><div className="page-heading"><div><p className="eyebrow">{view==='Сегодня'?'СЕГОДНЯ':'FOCUSBASE'}</p><h1>{view==='Настройки'?'Настройки и данные':view}</h1></div></div>{view==='Сегодня'?<TodayView/>:view==='Задачи'?<TasksView/>:view==='Проекты'?<ProjectsView/>:view==='Фокус'?<FocusView/>:view==='Библиотека'?<LibraryView/>:view==='Заметки'?<NotesView/>:view==='Мои таблицы'?<TablesView/>:view==='План недели'?<WeekView/>:view==='Настройки'?<SettingsView/>:<ArchiveView trash={view==='Корзина'}/>}</main></SidebarInset></SidebarProvider>{editing&&<Modal key={editing.kind+':'+(editing.id||'new')} title={titles[editing.kind]||'Запись'} close={()=>edit(null)} wide={['tasks','notes','resources'].includes(editing.kind)}>{editing.kind==='tasks'?<TaskForm {...editing}/>:editing.kind==='resources'?<ResourceForm {...editing}/>:editing.kind==='notes'?<NoteForm {...editing}/>:editing.kind==='projects'?<ProjectForm {...editing}/>:editing.kind==='tables'?<TableForm/>:editing.kind==='finish'?<FinishForm/>:editing.kind==='search'?<SearchForm/>:<QuickForm/>}</Modal>}{toast&&<div className="toast" role="status">{toast}<button aria-label="Закрыть уведомление" onClick={()=>setToast('')}>×</button></div>}</AppContext.Provider>}
