'use client';
import {useEffect,useState} from 'react';
import {Focus,Timer,Play,Pause,Check,CalendarDays,ListTodo,NotebookPen,LibraryBig,X,SkipForward,ArrowUp,ArrowDown,ListMusic} from 'lucide-react';
import {Popover,PopoverTrigger,PopoverContent} from '@/components/ui/popover';
import {requireActive,elapsed,phaseLimit,pause,nextPhase,startFocus,localDay} from '@/lib/focusbase/domain';
import {companionQueue,selectCompanionTask,moveCompanionTask,playCompanionTask,skipCompanionTask} from '@/lib/focusbase/companion-queue';
import {useApp,type Edit} from './ui';
import {ContextMenu,ContextMenuTrigger,ContextMenuContent,ContextMenuItem} from '@/components/ui/context-menu';
import {useCompanionPosition} from './use-companion-position';

const timeText=(ms:number)=>{const seconds=Math.floor(Math.max(0,ms)/1000);return `${Math.floor(seconds/60).toString().padStart(2,'0')}:${(seconds%60).toString().padStart(2,'0')}`};
export function Companion({hidden=false,desktop=false}:{hidden?:boolean;desktop?:boolean}){
  const {s,run,go,edit,language}=useApp();const en=language==='en';const l=(ru:string,eng:string)=>en?eng:ru;
  const [open,setOpen]=useState(false),[now,setNow]=useState(()=>Date.now()),[busy,setBusy]=useState(false);
  const [nativeApp,setNativeApp]=useState(false),[showQueue,setShowQueue]=useState(false);
  useEffect(()=>{queueMicrotask(()=>setNativeApp(!!window.focusbaseDesktop))},[]);
  const positionProps=useCompanionPosition(desktop);
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
  const a=s.active;const today=localDay(s.settings.timezone,now);const queue=companionQueue(s);const selected=queue[0];const next=queue.find(t=>t.id!==a?.taskId);
  const activeTask=s.tasks.find(t=>t.id===a?.taskId);const locked=activeTask?.status==='missed';const limit=a?phaseLimit(a):0;const passed=a?elapsed(a,now):0;const ended=!!a&&passed>=limit;
  const clock=a?timeText(a.mode==='free'?passed:limit-passed):'';
  const changeOpen=(value:boolean)=>{setOpen(value);if(desktop)void window.focusbaseDesktop?.setExpanded(value)};
  const navigate=(view:string)=>{changeOpen(false);go(view)};
  const form=(value:Edit)=>{changeOpen(false);edit(value)};
  async function change(fn:Parameters<typeof run>[0]){setBusy(true);try{return await run(fn)}finally{setBusy(false)}}
  const nextDate=next&&[next.date,next.deadline].filter(Boolean).sort()[0];
  const dateLabel=nextDate?new Intl.DateTimeFormat(en?'en-GB':'ru-RU',{day:'numeric',month:'short'}).format(new Date(nextDate+'T12:00:00')):l('Без даты','Unscheduled');
  if(hidden||(!desktop&&(!s.settings.companionVisible||nativeApp)))return null;
  return <Popover open={open} onOpenChange={changeOpen}>{desktop&&<div className="desktop-drag-handle" title={l('Перетащить иконку','Drag companion')}>•••</div>}
    <ContextMenu><ContextMenuTrigger asChild disabled={desktop}><PopoverTrigger asChild><button {...positionProps} onContextMenu={e=>{if(desktop){e.preventDefault();window.focusbaseDesktop?.showMenu(en)}}} onKeyDown={e=>{if(desktop&&(e.key==='ContextMenu'||(e.shiftKey&&e.key==='F10'))){e.preventDefault();window.focusbaseDesktop?.showMenu(en)}}} data-localized className={'companion-launcher '+(a?'has-timer':'')} aria-label={l('Открыть быстрый доступ ÇalışBase','Open ÇalışBase quick access')} title={l('Нажми, чтобы открыть. Потяни, чтобы переместить.','Click to open. Drag to move.')}><Focus size={25} strokeWidth={1.8}/>{a&&<span aria-hidden="true">{ended?<Check size={15}/>:a.runSince===null?<Pause size={14}/>:clock}</span>}</button></PopoverTrigger></ContextMenuTrigger>{!desktop&&<ContextMenuContent data-localized><ContextMenuItem onSelect={()=>{changeOpen(false);void run(d=>{d.settings.companionVisible=false})}}><X size={16}/>{l('Убрать иконку','Hide icon')}</ContextMenuItem></ContextMenuContent>}</ContextMenu>
    <PopoverContent data-localized side="top" align="end" sideOffset={12} collisionPadding={12} className="companion-panel" aria-label={l('Быстрый доступ ÇalışBase','ÇalışBase quick access')}>
      <div className="companion-heading"><span><Focus size={18}/>ÇalışBase</span><button className="icon-button" onClick={()=>changeOpen(false)} aria-label={l('Закрыть панель','Close panel')}><X size={18}/></button></div>
      {a?<section className="companion-timer"><p>{ended?l('Интервал завершён','Interval complete'):a.runSince===null?l('На паузе','Paused'):a.phase==='break'?l('Перерыв','Break'):l('В фокусе','Focusing')}</p><strong className="companion-clock" role="timer" aria-label={l('Время таймера','Timer time')}>{clock}</strong><button className="companion-task-title" onClick={()=>activeTask?form({kind:'tasks',id:activeTask.id}):navigate('Фокус')}>{activeTask?.title||l('Свободный фокус','Free focus')}</button><div className="companion-timer-actions">
        {!ended&&!locked&&<button className="secondary" disabled={busy} onClick={()=>void change(d=>{if(d.active?.id!==a.id)return;if(d.active.runSince===null)d.active.runSince=Date.now();else pause(d.active)})}>{a.runSince===null?<Play size={16}/>:<Pause size={16}/>} {a.runSince===null?l('Продолжить','Resume'):l('Пауза','Pause')}</button>}
        {ended&&!locked&&a.mode==='pomodoro'&&<button className="secondary" disabled={busy} onClick={()=>void change(d=>{if(d.active?.id===a.id)nextPhase(d)})}>{a.phase==='work'?l('Начать перерыв','Start break'):l('Следующий фокус','Next focus')}</button>}
        <button className="primary" disabled={busy||!next} onClick={()=>void change(d=>skipCompanionTask(d,a.taskId,a.id,true))}><SkipForward size={16}/>{l('Следующая','Next task')}</button>
      </div><div className="companion-session-links"><button className="text-link" disabled={busy} onClick={()=>void change(d=>skipCompanionTask(d,a.taskId,a.id,false))}>{l('Отложить','Put aside')}</button><button className="text-link" disabled={busy} onClick={async()=>{if(await change(d=>{pause(requireActive(d,a.id))}))form({kind:'finish',id:a.id})}}><Check size={14}/>{l('Завершить','Finish')}</button><button className="text-link" onClick={()=>navigate('Фокус')}><Timer size={14}/>{l('Таймер','Timer')}</button></div><p className="companion-switch-hint">{l('При переключении время сохранится, задача останется незавершённой.','Switching saves your time and leaves the task unfinished.')}</p></section>:<section className="companion-start"><p>{l('С чего начнём?','Where shall we start?')}</p>{selected?<><strong className="companion-task-title" data-no-translate>{selected.title}</strong><div className="companion-timer-actions"><button className="primary" disabled={busy} onClick={()=>void change(d=>playCompanionTask(d,selected.id,null))}><Play size={17}/>{l('Начать','Start')} · {selected.minutes} {l('мин','min')}</button><button className="secondary" disabled={busy||queue.length<2} onClick={()=>void change(d=>skipCompanionTask(d,selected.id,null,false))}><SkipForward size={16}/>{l('Пропустить','Skip')}</button></div></>:<button className="primary" disabled={busy} onClick={()=>void change(d=>startFocus(d,'','countdown',25,5))}><Play size={17}/>{l('25 минут фокуса','25 minutes of focus')}</button>}<button className="text-link" onClick={()=>navigate('Фокус')}><Timer size={15}/>{l('Настроить таймер','Set up timer')}</button></section>}
      <section className="companion-next"><button className="companion-queue-toggle" aria-expanded={showQueue} onClick={()=>setShowQueue(value=>!value)}><ListMusic size={18}/>{l('Выбрать задачу','Choose a task')}<span>{queue.length}</span></button>
        {showQueue?<><p className="companion-meta">{a?l('Нажми на задачу, чтобы переключиться. Стрелки меняют порядок.','Select a task to switch. Use arrows to reorder.'):l('Выбери первую задачу. Стрелки меняют порядок очереди.','Choose your first task. Use arrows to reorder the queue.')}</p><ol className="companion-queue" aria-label={l('Очередь задач','Task queue')}>{queue.map((task,index)=><li key={task.id} data-task-id={task.id} className={(a?task.id===a.taskId:task.id===selected?.id)?'is-selected':''}><button className="companion-queue-pick" disabled={busy} aria-pressed={a?task.id===a.taskId:task.id===selected?.id} onClick={()=>void change(d=>a?playCompanionTask(d,task.id,a.id):selectCompanionTask(d,task.id))}><span className="companion-queue-number">{index+1}</span><span><strong data-no-translate>{task.title}</strong><small>{task.minutes} {l('мин','min')}{task.id===a?.taskId?' · '+l('Сейчас','Playing'):''}</small></span></button><div className="companion-queue-move"><button className="icon-button" disabled={busy||index===0} aria-label={l('Выше: ','Move up: ')+task.title} onClick={()=>void change(d=>moveCompanionTask(d,task.id,-1))}><ArrowUp size={15}/></button><button className="icon-button" disabled={busy||index===queue.length-1} aria-label={l('Ниже: ','Move down: ')+task.title} onClick={()=>void change(d=>moveCompanionTask(d,task.id,1))}><ArrowDown size={15}/></button></div></li>)}</ol>{!queue.length&&<p className="companion-meta">{l('Открытых задач пока нет.','No open tasks yet.')}</p>}</>:a&&next?<div className="companion-upcoming"><p className="companion-label">{l('Следом','Up next')}</p><strong data-no-translate>{next.title}</strong><p className="companion-meta">{dateLabel} · {next.minutes} {l('мин','min')}</p></div>:<p className="companion-meta">{l('Можно выбрать любую задачу и менять порядок без галочек.','Choose any task and reorder without marking it complete.')}</p>}
      </section>
      <div className="companion-shortcuts"><button onClick={()=>form({kind:'tasks',date:today})}><ListTodo size={19}/>{l('Новая задача','New task')}</button><button onClick={()=>form({kind:'notes'})}><NotebookPen size={19}/>{l('Заметка','Note')}</button><button onClick={()=>navigate('Календарь')}><CalendarDays size={19}/>{l('Календарь','Calendar')}</button><button onClick={()=>navigate('Библиотека')}><LibraryBig size={19}/>{l('Материалы','Resources')}</button></div>
    </PopoverContent>
  </Popover>
}
