'use client';
import {useEffect,useState} from 'react';
import {Monitor} from 'lucide-react';
import {useApp,Check,type Edit} from './ui';
declare global{interface Window{focusbaseDesktop?:{mini:boolean;getEnabled:()=>Promise<boolean>;setEnabled:(value:boolean)=>Promise<boolean>;setExpanded:(value:boolean)=>Promise<void>;drag:(phase:'start'|'move'|'end')=>void;open:(payload:{view?:string;edit?:Edit})=>Promise<void>;onOpen:(callback:(payload:{view?:string;edit?:Edit})=>void)=>()=>void}}}
export function DesktopSettings(){
  const {language}=useApp();const en=language==='en';const [available,setAvailable]=useState(false),[enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{const bridge=window.focusbaseDesktop;if(bridge){setAvailable(true);void bridge.getEnabled().then(setEnabled).catch(()=>setError(en?'Unable to read desktop settings':'Не удалось прочитать настройки'))}},[en]);
  return <section data-localized className="panel form-stack"><h2><Monitor size={21}/> {en?'Desktop companion':'Иконка на рабочем столе'}</h2>{available?<><Check checked={enabled} onChange={async value=>{if(busy)return;setBusy(true);try{setEnabled(await window.focusbaseDesktop!.setEnabled(value));setError('')}catch{setError(en?'Could not change desktop settings':'Не удалось изменить настройки')}finally{setBusy(false)}}}>{en?'Show above other windows':'Показывать поверх других окон'}</Check><p className="muted">{en?'Drag the handle above the icon to move it. Closing the main window keeps the companion running. Use the tray menu to quit completely.':'Перетаскивай иконку за ручку сверху. После закрытия главного окна она продолжит работать. Полностью выйти можно через значок FocusBase рядом с часами Windows.'}</p><p className="muted">{en?'Browser and desktop data are separate. Transfer your workspace using a JSON backup below.':'У браузера и настольной версии отдельные данные. Перенеси своё пространство через JSON-копию в разделе ниже.'}</p></>:<><p>{en?'To keep the icon outside the browser, open FocusBase Desktop for Windows. Enable “Show above other windows” in its settings.':'Для иконки за пределами браузера открой FocusBase Desktop для Windows. В его настройках включи «Показывать поверх других окон».'}</p><p className="muted">{en?'Export your data here, then restore the backup in the desktop app.':'Сначала экспортируй данные здесь, затем восстанови копию в настольном приложении.'}</p></>}{error&&<p role="alert">{error}</p>}</section>
}
