export type Language='ru'|'en';

// UI copy lives here so the language switch can update every view, including
// forms and empty states that are mounted later through dialogs.
const copy:Record<string,string>={
  'СЕГОДНЯ':'TODAY','Сегодня':'Today','Задачи':'Tasks','Проекты':'Projects','Фокус':'Focus','Библиотека':'Library','Заметки':'Notes','Мои таблицы':'My tables','План недели':'Week plan','Архив':'Archive','Корзина':'Trash','Настройки':'Settings','Настройки и данные':'Settings & data',
  'ЛИЧНОЕ ПРОСТРАНСТВО':'PERSONAL SPACE','Данные на этом устройстве':'Data on this device','Моё пространство':'My space','Учёба · проекты · развитие':'Study · projects · growth','Я':'Me','Режим дня':'Day mode','мин':'min','минут':'minutes','шагов':'steps','задач':'tasks','факт':'actual',
  'Поиск':'Search','Поиск в пространстве':'Search workspace','Добавить':'Add','Повторить':'Retry','Язык интерфейса':'Interface language','Открываем ваше пространство…':'Opening your space…','Закройте другие вкладки ÇalışBase и обновите страницу.':'Close other ÇalışBase tabs and reload the page.','Не удалось открыть хранилище.':'Could not open local storage.','Не удалось сохранить:':'Could not save:','Офлайн · изменения останутся на этом устройстве':'Offline · changes stay on this device','Фокус на паузе':'Focus paused','Фокус запущен':'Focus running','Свободная сессия':'Free session','Вернуться →':'Return →','Фактическое время относительно плана':'Actual time against plan',
  'ВРЕМЯ ДЛЯ ОДНОЙ ЗАДАЧИ':'TIME FOR ONE TASK','Настройте свой ритм':'Set your rhythm','Обратный отсчёт':'Countdown','Свободный':'Free','Свободный таймер':'Free timer','Без задачи':'No task','Работа, минут':'Work, minutes','Перерыв, минут':'Break, minutes','Начать фокус':'Start focus','Звуки и уведомления выключены по умолчанию. Перерывы в Pomodoro начинаются по вашему нажатию.':'Sounds and notifications are off by default. Pomodoro breaks start when you press the button.',
  'ГЛАВНЫЙ ФОКУС':'MAIN FOCUS','МОЙ ДЕНЬ':'MY DAY','Откройте материал, начните занятие и сохраните результат.':'Open the material, start a session, and save the result.','Открыть задачу':'Open task','Прикрепить материал':'Attach material','Дальше по плану':'Up next','Все задачи':'All tasks','Сосредоточьтесь на главном':'Stay with the main thing','План пока свободен':'Your plan is open','Оставьте место для отдыха. Необязательно заполнять весь день.':'Leave room for rest. You do not need to fill every hour.','Выполнено сегодня':'Completed today','Осталось с прошлых дней':'Carried over','Ничего не переносим автоматически. Решите, что всё ещё актуально.':'Nothing is moved automatically. Decide what still matters.','На сегодня':'For today','Без даты':'No date','Отменить':'Cancel','Всё на сегодня выполнено':'Everything for today is done','Можно остановиться и отдохнуть. Или выбрать следующий небольшой шаг.':'You can stop and rest, or choose a small next step.','Одна понятная задача — уже хороший план.':'One clear task is already a good plan.','План можно менять в течение дня':'The plan can change during the day','Время на сегодня':'Time today','Запланировано':'Planned','В фокусе':'Focused','Время — ориентир, а не оценка.':'Time is a guide, not a grade.','Под рукой':'At hand','Добавьте материалы в избранное, чтобы быстро возвращаться к ним.':'Add materials to your favorites to return quickly.','Открыть библиотеку':'Open library','Освободить голову':'Clear your head','Ссылка':'Link','Задача':'Task','Заметка':'Note','Создать первую задачу':'Create first task','Прикрепите ссылки в карточке задачи.':'Attach links in the task card.','Первая сессия ещё впереди':'Your first session is ahead','После занятия здесь появится ваш результат.':'Your result will appear here after the session.','Без итога':'No summary','Дальше:':'Next:',
  'Никто не придёт спасать твой план.':'No one is coming to save your plan.','Время не вернётся. Пропущенная практика сама не станет навыком.':'Time will not return. Missed practice will not become skill on its own.','Намерение ничего не меняет. Меняет только действие.':'Intention changes nothing. Action changes everything.','Каждый отданный прокрастинации день потом оплачивается усилием.':'Every day given to procrastination is paid back with effort.','Талант без повторений проигрывает тому, кто продолжает.':'Talent without repetition loses to the one who keeps going.','Цель не обязана случиться. Без часов работы это только желание.':'A goal does not happen by itself. Without hours of work, it is only a wish.','Самая неприятная конкуренция — с версией себя, которой ты мог стать.':'The hardest competition is with the person you could have become.',
  'Список':'List','Новая задача':'New task','Активные':'Active','Все статусы':'All statuses','Все направления':'All directions','Все приоритеты':'All priorities','По приоритету':'By priority','По дате':'By date','По названию':'By title','Название, описание или тег':'Title, description or tag','Фильтр статуса':'Status filter','Фильтр направления':'Direction filter','Приоритет':'Priority','Сортировка задач':'Task sorting','Задачи не найдены':'No tasks found','Измените фильтры или добавьте новую задачу.':'Change the filters or add a new task.','Добавить задачу':'Add task','Главная задача дня':'Main task of the day','Входящие':'Inbox','К выполнению':'To do','В работе':'In progress','Готово':'Done','Отменена':'Cancelled','Сохраните ссылку вручную — название и URL уже достаточно.':'Save the link manually — a title and URL are enough.','Пример':'Example',
  'Задачи и материалы вокруг одного результата.':'Tasks and materials around one outcome.','Новый проект':'New project','Изменить':'Edit','задач выполнено':'tasks completed','+ Материал':'+ Material','+ Заметка':'+ Note','От идеи к результату':'From idea to outcome','Создайте проект для подготовки к экзамену, приложения или поступления.':'Create a project for an exam, an app, or an application.','Создать проект':'Create project',
  'Сохраняйте с понятной причиной вернуться.':'Save things with a clear reason to return.','Сохранить материал':'Save material','Название, ссылка, заметка или тег':'Title, link, note or tag','Сохранено':'Saved','Изучаю':'Studying','Изучено':'Studied','Материалы не найдены':'No materials found','Изменить материал':'Edit material','Избранное:':'Favorite:',
  'Поиск в заметках':'Search notes','Новая заметка':'New note','Пустая заметка':'Empty note','Связана с задачей':'Linked to a task','Мысли, к которым хочется вернуться':'Thoughts worth returning to','Конспекты, разбор ошибок, планы и итоги — рядом с вашими задачами.':'Notes, error reviews, plans and reflections — alongside your tasks.','Создать заметку':'Create note',
  'Что найти?':'What are you looking for?','Общий поиск':'Global search','Поиск по задачам, заметкам, материалам и содержимому таблиц.':'Search tasks, notes, materials and table contents.','Ничего не найдено':'Nothing found','Быстрое добавление':'Quick add','Ссылка или материал':'Link or material','К чему вернуться позже':'Something to return to later','Мысль, конспект или результат':'A thought, note or result',
  'Таймер на паузе. Время заполнения итога не засчитывается.':'Timer paused. Time spent writing the summary is not counted.','Что сделал':'What did you do?','Результат':'Result','Например: 11/13, ошибки в True / False':'For example: 11/13, errors in True / False','Следующий шаг':'Next step','Отметить задачу выполненной':'Mark task as complete','Сохраняю…':'Saving…','Сохранить итог':'Save summary','Сохранить':'Save','В корзину':'Move to trash','В архив':'Archive',
  'Материалы к задаче':'Task materials','Отвлекающая мысль':'Distracting thought','Записать и вернуться к делу':'Write it down and return to the task','Сохранить мысль':'Save thought','Интервал завершён':'Interval complete','Перерыв завершён. Можно вернуться к задаче.':'Break complete. Return to the task.','Начать перерыв':'Start break','Следующий фокус':'Next focus','Продолжить':'Resume','Пауза':'Pause','Завершить':'Finish','На паузе':'Paused','Можно сосредоточиться':'Ready to focus','Рабочее время:':'Work time:','завершено интервалов:':'intervals completed:','Последние сессии':'Recent sessions',
  'Рабочее пространство':'Workspace','Тема':'Theme','Светлая':'Light','Тёмная':'Dark','Часовой пояс IANA':'IANA time zone','Сохранить часовой пояс':'Save time zone','Даты задач — календарные дни. Таймер хранит абсолютные временные отметки. Интерфейс сейчас на русском.':'Task dates use calendar days. The timer stores absolute timestamps. The interface is currently in Russian.','Звук завершения интервала':'Interval completion sound','Уведомления о завершении интервала':'Interval completion notifications','Данные и резервные копии':'Data and backups','Данные находятся в IndexedDB этого браузера. Они не отправляются на сервер. Другой браузер, адрес сайта или устройство имеет отдельное хранилище.':'Data is stored in this browser’s IndexedDB. It is not sent to a server. Another browser, site address, or device has separate storage.','Экспорт всех данных':'Export all data','Восстановить резервную копию':'Restore backup','Запросить постоянное хранение':'Request persistent storage','Очистка данных браузера удалит локальные записи. JSON сохраняет связи, настройки, корзину и таймер. CSV предназначен для отдельных таблиц.':'Clearing browser data removes local records. JSON keeps links, settings, trash and the timer. CSV is for individual tables.','Познакомиться с приложением':'Explore the app','Можно добавить небольшой набор с меткой «Пример». Он удаляется отдельно от ваших данных.':'Add a small set marked “Example”. It can be removed separately from your data.','Добавить примеры':'Add examples','Убрать только примеры':'Remove examples','Предпросмотр резервной копии':'Backup preview','Проверьте содержимое перед восстановлением.':'Review the contents before restoring.','Перейти к восстановлению':'Continue to restore','Заменить данные пространства?':'Replace workspace data?','Отмена':'Cancel','Заменить и восстановить':'Replace and restore','Корзина пуста':'Trash is empty','Архив пуст':'Archive is empty','Удалённые записи можно восстановить. Окончательного удаления в этой версии нет.':'Deleted records can be restored. Permanent deletion is not available in this version.','Сохранённые записи, которые сейчас не нужны в работе.':'Saved records that are not currently needed.','Восстановить':'Restore','Запись восстановлена':'Record restored','Строка восстановлена':'Row restored','Часовой пояс:':'Time zone:','Пустая строка':'Empty row',
  'Новая таблица':'New table','Университеты':'Universities','Результаты пробников':'Mock test results','Проекты и достижения':'Projects and achievements','Личный список ресурсов':'Personal resource list','Название':'Name','Страна':'Country','Программа':'Program','Дедлайн':'Deadline','Источник':'Source','Стоимость':'Cost','Учебный год':'Academic year','Проверено':'Checked','Тест':'Test','Раздел':'Section','Максимум':'Maximum','Условия':'Conditions','Мой вклад':'My contribution','Подтверждение':'Evidence','Строка':'Row','Колонки':'Columns','Удалить строку':'Delete row','Добавить строку':'Add row','Добавить колонку':'Add column','Импорт CSV':'Import CSV','Экспорт CSV':'Export CSV',
  'Предыдущая неделя':'Previous week','Следующая неделя':'Next week','Фиксированное событие':'Fixed event','Добавить событие':'Add event','Неразобранные задачи':'Unscheduled tasks','Перенести':'Move','Удалить':'Delete','Событие':'Event','Время':'Time','Описание':'Description'
};

const extra:Record<string,string>={
  'Поиск задач':'Search tasks','Английский / IELTS':'English / IELTS','Математика / SAT':'Math / SAT','Школа':'School','Программирование':'Programming','Поступление':'Applications','Личное':'Personal',
  'С чего начнём сегодня?':'Where do we start today?','Изменения сохраняются в вашем личном пространстве.':'Changes are saved in your personal space.','Что нужно сделать':'What needs to be done?','Направление':'Direction','Проект':'Project','Статус':'Status','День выполнения':'Due date','Жёсткий дедлайн (необязательно)':'Hard deadline (optional)','План, минут':'Plan, minutes','Повторение после завершения':'Repeat after completion','Не повторять':'Do not repeat','Каждый день':'Every day','Каждую неделю':'Every week','Время (например, 16:40–17:20)':'Time (for example, 16:40–17:20)','После события':'After event','После ужина':'After dinner','Теги через запятую':'Tags, separated by commas','Чек-лист':'Checklist','Новый пункт чек-листа':'New checklist item','Сначала сохраните ссылку в библиотеке или через «Добавить».':'Save a link in Library or through “Add” first.','Открыть':'Open','Заметки и результаты':'Notes and results','Фактическое время:':'Actual time:','Добавить заметку':'Add note','Начать фокус по сохранённой задаче':'Start focus on saved task','Название проекта':'Project name','Какой результат хочу получить':'What outcome do I want?','URL':'URL','Тип':'Type','Коллекция':'Collection','Прикрепить к задаче':'Attach to task','Зачем мне это':'Why do I need this?','В избранное':'Add to favorites','Эта ссылка уже есть в библиотеке. Свяжите существующий материал с задачей.':'This link is already in the library. Link the existing material to the task.','Эта ссылка уже сохранена:':'This link is already saved:','Выберите её в задаче.':'Choose it in the task.','Заголовок заметки':'Note title','Шаблон заметки':'Note template','Вставить шаблон':'Insert template','Редактировать':'Edit','Предпросмотр':'Preview','Markdown · автосохранение':'Markdown · autosave','Текст заметки':'Note text','Начните писать… Поддерживаются # заголовки, списки, [ссылки](https://…), `код`.':'Start writing… Supports # headings, lists, [links](https://…), and `code`.','Ресурс':'Resource','Закрепить заметку':'Pin note','Сохранить и закрыть':'Save and close','Есть изменения':'Unsaved changes','Ошибка сохранения':'Save error',
  'Никто не придёт спасать твой план.':'No one is coming to save your plan.','Время не вернётся. Пропущенная практика сама не станет навыком.':'Time will not return. Missed practice will not become skill on its own.','Намерение ничего не меняет. Меняет только действие.':'Intention changes nothing. Action changes everything.','Каждый отданный прокрастинации день потом оплачивается усилием.':'Every day given to procrastination is paid back with effort.','Талант без повторений проигрывает тому, кто продолжает.':'Talent without repetition loses to the one who keeps going.','Цель не обязана случиться. Без часов работы это только желание.':'A goal does not happen by itself. Without hours of work, it is only a wish.','Самая неприятная конкуренция — с версией себя, которой ты мог стать.':'The hardest competition is with the person you could have become.',
  'Статья':'Article','Видео':'Video','Курс':'Course','Учебник':'Textbook','Документ':'Document','Инструмент':'Tool','Поиск материалов':'Search materials','Направление материалов':'Material direction','Тип материалов':'Material type','Статус материала':'Material status','Сохранить ссылку':'Save link','Поиск заметок':'Search notes','Свои данные. Своя структура. Import CSV':'Your data. Your structure. Import CSV','Место для ваших таблиц':'A place for your tables','Сравнивайте университеты, записывайте пробники и достижения.':'Compare universities, track mock tests and achievements.','Создать таблицу':'Create table','Эта неделя':'This week','Добавить школьный распорядок':'Add school routine','Сохранить задачи как шаблон':'Save tasks as template','Шаблон недели':'Week template','Применить':'Apply','Задачи можно перетащить на день или изменить дату в карточке. Свободное время остаётся свободным.':'Drag tasks to a day or change the date in the task card. Free time stays free.','задач':'tasks','Пн':'Mon','Вт':'Tue','Ср':'Wed','Че':'Thu','Пя':'Fri','Су':'Sat','Во':'Sun','По':'Mon'
};
const studyCopy:Record<string,string>={
'Обзор недели':'Weekly review',
'Календарь':'Calendar','Календарь месяца':'Month calendar','Экзамены':'Exams','ПОДГОТОВКА':'EXAM PREP','UNT / ҰБТ':'UNT / ҰБТ',
'Дополнительно':'More options','Новая цель':'New goal','Изменить цель':'Edit goal','Новая цель экзамена':'New exam goal','Цели экзаменов':'Exam goals','События календаря':'Calendar events',
'Новое событие':'New event','Изменить событие':'Edit event','Своя цитата':'Your quote','Событие':'Event','Цель':'Goal','Материал сохранён':'Material saved','Цитата обновлена':'Quote updated',
'Занятие, пробник или встреча':'Session, mock test or meeting','Материал':'Material','Без связи':'No link','Все типы':'All types','Все коллекции':'All collections','Закрыть':'Close','Перемещено в корзину':'Moved to trash',
'Например: IELTS Reading — Passage 2':'For example: IELTS Reading — Passage 2','Что сделать и какой результат получить?':'What will you do, and what is the expected result?'
};
const allCopy={...copy,...extra,...studyCopy};

const weekdays:Record<string,string>={понедельник:'Monday',вторник:'Tuesday',среда:'Wednesday',четверг:'Thursday',пятница:'Friday',суббота:'Saturday',воскресенье:'Sunday'};
const months:Record<string,string>={января:'January',февраля:'February',марта:'March',апреля:'April',мая:'May',июня:'June',июля:'July',августа:'August',сентября:'September',октября:'October',ноября:'November',декабря:'December'};
const shortWeekdays:Record<string,string>={пн:'Mon',вт:'Tue',ср:'Wed',че:'Thu',пя:'Fri',су:'Sat',во:'Sun'};

function preserveCase(value:string,replacement:string){return value[0]===value[0].toUpperCase()?replacement[0].toUpperCase()+replacement.slice(1):replacement}
function tokenReplace(value:string,map:Record<string,string>){return value.replace(/\p{L}+/gu,token=>map[token.toLowerCase()]?preserveCase(token,map[token.toLowerCase()]):token)}

export function translateText(value:string,language:Language){
  if(language==='ru')return value;
  const trimmed=value.trim();
  if(!trimmed)return value;
  const table=allCopy;
  const direct=table[trimmed];
  if(direct!==undefined)return value.replace(trimmed,direct);
  if(language==='en'){
    const next=value.replace(/из\s+(\d+)\s+задач\s+выполнено/gu,'of $1 tasks completed').replace(/(\d+)\s+минут(?!\p{L})/gu,'$1 minutes').replace(/(\d+)\s+мин(?!\p{L})/gu,'$1 min').replace(/(\d+)\s+шагов(?!\p{L})/gu,'$1 steps').replace(/(\d+)\s+задач(?!\p{L})/gu,'$1 tasks').replace(/min\s+задач/gu,'min tasks').replace(/(?<!\p{L})минут(?!\p{L})/gu,'minutes').replace(/(?<!\p{L})мин(?!\p{L})/gu,'min').replace(/(?<!\p{L})задач(?!\p{L})/gu,'tasks').replace(/(?<!\p{L})факт(?!\p{L})/gu,'actual').replace(/(?<!\p{L})приоритет(?!\p{L})/gu,'priority').replace(/^Начать фокус:/,'Start focus:').replace(/^Завершить /,'Complete ').replace(/^Избранное:/,'Favorite:');
    return tokenReplace(next,{...weekdays,...months,...shortWeekdays});
  }
  return value;
}

const sourceText=new WeakMap<Text,{source:string;rendered:string}>();
const sourceAttributes=new WeakMap<HTMLElement,Map<string,{source:string;rendered:string}>>();
export function translateDocument(language:Language){
  if(typeof document==='undefined')return;
  const walk=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);
  const nodes:Text[]=[];let node:Node|null;
  while((node=walk.nextNode()))nodes.push(node as Text);
  for(const text of nodes){
    if(text.parentElement?.closest('script,style,textarea,input,[contenteditable="true"],[data-no-translate],[data-localized]'))continue;
    const value=text.nodeValue||'';const prior=sourceText.get(text);const source=prior?.rendered===value?prior.source:value;const next=translateText(source,language);sourceText.set(text,{source,rendered:next});
    if(next!==text.nodeValue)text.nodeValue=next;
  }
  for(const el of Array.from(document.querySelectorAll<HTMLElement>('[aria-label],[placeholder],[title]'))){
    if(el.closest('[data-no-translate],[data-localized]'))continue;
    for(const attr of ['aria-label','placeholder','title'] as const){const value=el.getAttribute(attr);if(value){let attrs=sourceAttributes.get(el);if(!attrs){attrs=new Map();sourceAttributes.set(el,attrs)}const prior=attrs.get(attr);const source=prior?.rendered===value?prior.source:value;const next=translateText(source,language);attrs.set(attr,{source,rendered:next});if(next!==value)el.setAttribute(attr,next)}}
  }
  document.documentElement.lang=language==='en'?'en':'ru';
}
