'use client';
import {TaskDuration} from './task-duration';
import {useState} from 'react';
import {Plus,Repeat2,Play,ArrowRight,ChevronLeft,ChevronRight,NotebookPen,Check,Undo2} from 'lucide-react';
import {useApp,TextInput,Select,SafeLink} from './ui';
import {addDays,baseRecord,directions,localDay,taskSchema,visible,weekStart,type Resource} from '@/lib/focusbase/domain';
import {practiceResource,recordReview,reviewIntervals,scheduleReview,weeklyNote,weekReport} from '@/lib/focusbase/learning';
import {translateText} from './i18n';

export function QuickCapture(){
  const {s,run,edit,language}=useApp();const en=language==='en';const l=(ru:string,eng:string)=>en?eng:ru;
  const [title,setTitle]=useState(''),[day,setDay]=useState('today'),[minutes,setMinutes]=useState('25'),[direction,setDirection]=useState<string>(directions[0]),[busy,setBusy]=useState(false),[created,setCreated]=useState('');
  const today=localDay(s.settings.timezone);const date=day==='today'?today:day==='tomorrow'?addDays(today,1):'';
  return <section className="quick-capture" data-localized aria-label={l('Быстрая задача','Quick task')}><form onSubmit={async e=>{e.preventDefault();if(busy||!title.trim())return;setBusy(true);const id=crypto.randomUUID();const ok=await run(d=>{d.tasks.push(taskSchema.parse({...baseRecord(title.trim()),id,date,minutes:Number(minutes),direction,status:date?'todo':'inbox'}))});setBusy(false);if(ok){setTitle('');setCreated(id)}}}>
    <div className="capture-line"><Plus size={20}/><TextInput maxLength={500} required value={title} onChange={e=>setTitle(e.target.value)} aria-label={l('Название быстрой задачи','Quick task title')} placeholder={l('Что сделаешь следующим?','What will you do next?')}/><button type="submit" className="primary" disabled={busy||!title.trim()}>{l('Добавить','Add')}</button></div>
    <div className="capture-options"><Select label={l('День задачи','Task day')} value={day} onChange={setDay} options={ [['today',l('Сегодня','Today')],['tomorrow',l('Завтра','Tomorrow')],['inbox',l('Без даты','Unscheduled')]]}/><TaskDuration compact value={minutes} onChange={setMinutes}/><Select label={l('Направление','Subject')} value={direction} onChange={setDirection} options={directions.map(d=>[d,translateText(d,language)])}/></div>
  </form>{created&&<div className="capture-success" role="status"><Check size={16}/><span>{l('Задача добавлена','Task added')}</span><button onClick={()=>edit({kind:'tasks',id:created})}>{l('Открыть','Open')}</button><button disabled={busy} onClick={async()=>{setBusy(true);const ok=await run(d=>{if(d.active?.taskId===created)throw Error(l('Сначала завершите фокус по этой задаче.','Finish this task’s focus session first.'));const t=d.tasks.find(t=>t.id===created);if(t)t.deletedAt=Date.now()});setBusy(false);if(ok)setCreated('')}}><Undo2 size={14}/>{l('Отменить','Undo')}</button></div>}</section>
}

export function ResourceStudyActions({resource}:{resource:Resource}){
  const {s,run,edit,language}=useApp();const en=language==='en';const l=(ru:string,eng:string)=>en?eng:ru;const [busy,setBusy]=useState(false);const today=localDay(s.settings.timezone);
  return <div data-localized className="resource-study-actions"><button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);let id='';const ok=await run(d=>{id=practiceResource(d,resource.id,today,en)});setBusy(false);if(ok)edit({kind:'tasks',id})}}><Play size={16}/>{l('Практиковаться','Practice')}</button><button className="text-link" disabled={busy} onClick={async()=>{setBusy(true);await run(d=>{const r=d.resources.find(x=>x.id===resource.id);if(!r)return;if(r.review)r.review=null;else scheduleReview(d,r.id,today)},resource.review?l('Повторения выключены','Reviews turned off'):l('Материал добавлен в повторения','Added to reviews'));setBusy(false)}}><Repeat2 size={16}/>{resource.review?l('Убрать из повторений','Stop reviewing'):l('Повторять','Review later')}</button>{resource.review&&<small>{l('Следующее повторение: ','Next review: ')}{resource.review.due}</small>}</div>
}

export function ReviewQueue({compact=false}:{compact?:boolean}){
  const {s,run,edit,language}=useApp();const en=language==='en';const l=(ru:string,eng:string)=>en?eng:ru;const [busy,setBusy]=useState('');const today=localDay(s.settings.timezone);
  const tracked=s.resources.filter(r=>visible(r)&&r.review);const due=tracked.filter(r=>r.review!.due<=today).sort((a,b)=>a.review!.due.localeCompare(b.review!.due));
  const next=tracked.filter(r=>r.review!.due>today).sort((a,b)=>a.review!.due.localeCompare(b.review!.due))[0];
  if(compact&&!tracked.length)return null;
  return <section data-localized className="review-queue"><div className="section-title"><h2><Repeat2 size={20}/>{l('Пора повторить','Time to review')}</h2><span>{due.length}</span></div><p className="muted">{due.length?l('Сначала вспомни без подсказок. Затем открой материал и проверь себя.','Recall without hints first. Then open the resource and check yourself.'):next?l('Всё повторено. Следующий материал: ','All caught up. Next resource: ')+next.review!.due:l('Нажми «Повторять» у материала. Здесь появится расписание возвращений к нему.','Choose “Review later” on a resource to start its review schedule.')}</p>
    {due.slice(0,compact?3:undefined).map(r=><article className="review-item" key={r.id}><div><SafeLink url={r.url}>{r.title}</SafeLink><small>{l('Назначено: ','Scheduled: ')}{r.review!.due}</small></div><div className="review-buttons"><button className="secondary" disabled={!!busy} onClick={async()=>{setBusy(r.id);await run(d=>{recordReview(d,r.id,false,today,r.review!.due)});setBusy('')}}>{l('Ещё раз · завтра','Again · tomorrow')}</button><button className="primary" disabled={!!busy} onClick={async()=>{setBusy(r.id);await run(d=>{recordReview(d,r.id,true,today,r.review!.due)});setBusy('')}}><Check size={15}/>{l('Помню','Recalled')} · {reviewIntervals[Math.min(4,r.review!.step+1)]} {l('дн.','days')}</button><button className="icon-button" aria-label={l('Отложить на завтра: ','Snooze until tomorrow: ')+r.title} title={l('Отложить на завтра','Snooze until tomorrow')} disabled={!!busy} onClick={async()=>{setBusy(r.id);await run(d=>{const item=d.resources.find(x=>x.id===r.id);if(item?.review)item.review.due=addDays(today,1)});setBusy('')}}><ChevronRight size={18}/></button></div></article>)}
    {compact&&due.length>3&&<button className="text-link" onClick={()=>edit({kind:'resources',id:due[3].id})}>{l('Ещё материалов: ','More resources: ')}{due.length-3}</button>}
  </section>
}

export function WeekReview(){
  const {s,run,go,edit,language}=useApp();const en=language==='en';const l=(ru:string,eng:string)=>en?eng:ru;
  const thisWeek=weekStart(localDay(s.settings.timezone));const [offset,setOffset]=useState(0),[busy,setBusy]=useState(false);const start=addDays(thisWeek,offset*7);const report=weekReport(s,start);
  const dateLabel=(date:string)=>new Intl.DateTimeFormat(en?'en-GB':'ru-RU',{day:'numeric',month:'short'}).format(new Date(date+'T12:00:00'));
  const max=Math.max(30,...report.days.map(d=>Math.max(d.minutes,d.planned)));
  return <div data-localized className="week-review"><div className="week-review-toolbar"><div className="inline"><button className="secondary" aria-label={l('Предыдущая неделя','Previous week')} onClick={()=>setOffset(v=>v-1)}><ChevronLeft size={18}/></button><h2>{dateLabel(start)} — {dateLabel(addDays(start,6))}</h2><button className="secondary" disabled={offset===0} aria-label={l('Следующая неделя','Next week')} onClick={()=>setOffset(v=>Math.min(0,v+1))}><ChevronRight size={18}/></button></div><button className="text-link" onClick={()=>go('План недели')}>{l('Планировать неделю','Plan your week')}<ArrowRight size={17}/></button></div>
    <div className="review-metrics"><div><strong>{Math.round(report.minutes)}</strong><span>{l('минут в фокусе','minutes focused')}</span></div><div><strong>{report.activeDays}<small>/7</small></strong><span>{l('дней с практикой','days with practice')}</span></div><div><strong>{report.completed}<small>/{report.planned}</small></strong><span>{l('задач из плана выполнено','planned tasks completed')}</span></div></div>
    <section className="panel"><div className="section-title"><h2>{l('План и реальное время','Planned and actual time')}</h2><span className="muted">{l('минуты','minutes')}</span></div><div className="week-bars">{report.days.map(d=><div className="week-bar" key={d.date}><span>{new Intl.DateTimeFormat(en?'en-GB':'ru-RU',{weekday:'short'}).format(new Date(d.date+'T12:00:00'))}</span><div className="week-bar-track" aria-hidden="true"><div className="week-bar-plan" style={{width:(d.planned/max*100)+'%'}}/><div className="week-bar-actual" style={{width:(d.minutes/max*100)+'%'}}/></div><span aria-label={l('Факт / план','Actual / planned')}>{Math.round(d.minutes)} / {d.planned}</span></div>)}</div><p className="muted">{l('Зелёный — сохранённые фокус-сессии, светлый — план. Время сессии относится к дню её завершения.','Green shows saved focus sessions; light shows the plan. Session time is assigned to its completion day.')}</p></section>
    <div className="review-bottom"><section className="panel"><h2>{l('На что ушло время','Where your time went')}</h2>{Object.entries(report.byDirection).sort((a,b)=>b[1]-a[1]).map(([name,minutes])=><div className="subject-total" key={name}><span>{translateText(name,language)}</span><strong>{Math.round(minutes)} {l('мин','min')}</strong></div>)}{!report.sessions&&<p className="muted">{l('После первой сохранённой сессии здесь появится распределение по предметам.','Save your first focus session to see time by subject.')}</p>}</section><section className="panel review-reflection"><NotebookPen size={24}/><h2>{l('Одна неделя — один вывод','One week, one takeaway')}</h2><p>{l('Что сработало? Что мешало? Выбери одно изменение на следующую неделю.','What worked? What got in the way? Choose one change for next week.')}</p><button disabled={busy} className="primary" onClick={async()=>{setBusy(true);let id='';const ok=await run(d=>{id=weeklyNote(d,start,en)});setBusy(false);if(ok)edit({kind:'notes',id})}}>{l('Записать итог недели','Write your weekly review')}</button></section></div>
  </div>
}

export function ReviewShortcut(){const {go,language}=useApp();return <button data-localized className="review-shortcut" onClick={()=>go('Обзор недели')}><span>{language==='en'?'How is your week going?':'Как проходит твоя неделя?'}<small>{language==='en'?'Focus time, subjects and a weekly reflection':'Время занятий, предметы и итоги'}</small></span><ArrowRight size={19}/></button>}
