'use client';
import {useApp} from './ui';
import {useAccount} from './account';
export function StorageExplanation(){
  const {language}=useApp();const en=language==='en';const account=useAccount();
  if(account.user)return <div data-localized className="muted"><p>{en?'Your workspace is stored in your Supabase account. Database access rules separate accounts. Keep a JSON backup for an independent copy.':'Пространство хранится в твоём аккаунте в Supabase. Правила доступа базы разделяют данные пользователей. Сохраняй JSON-копию для независимой резервной копии.'}</p><p>{en?'Cloud saving requires internet access. Sign out on shared computers. Unsaved note drafts are kept separately for each account in this tab.':'Для облачного сохранения нужен интернет. Выходи из аккаунта на общих компьютерах. Несохранённые черновики заметок хранятся отдельно для каждого аккаунта в этой вкладке.'}</p></div>;
  if(account.enabled)return <p className="muted" data-localized>{en?'These records are stored only in this browser. People sharing this browser profile share this local workspace. Google accounts have separate cloud workspaces; local records are transferred only with your confirmation.':'Эти записи хранятся только в этом браузере. Люди в одном профиле браузера видят общее локальное пространство. У аккаунтов Google — отдельные облачные пространства; локальные записи переносятся только с твоего подтверждения.'}</p>;
  return <div data-localized className="muted"><p>{en?'Your records are stored locally in this browser (IndexedDB), not in a shared server database. Visitors using other devices or browser profiles have separate workspaces.':'Записи хранятся локально в этом браузере (IndexedDB), а не в общей серверной базе. У посетителей на других устройствах или в других профилях браузера — отдельные пространства.'}</p><p className="tail-note">{en?'There are no accounts or automatic sync. People sharing the same browser profile share this workspace; use separate browser profiles on a shared computer. Transfer data to another device using a JSON backup.':'Аккаунтов и автоматической синхронизации нет. Люди в одном профиле браузера используют общее пространство; на общем компьютере используйте разные профили браузера. Для переноса на другое устройство сохраните JSON-копию.'}</p></div>;
}
