import {spawnSync} from 'node:child_process';
import {createRequire} from 'node:module';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url);const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
require('@next/env').loadEnvConfig(root);
const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL,publishableKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
if(!supabaseUrl||!publishableKey)throw Error('Desktop cloud configuration is missing. Set the public Supabase URL and publishable key.');
const parsed=new URL(supabaseUrl);
if(parsed.protocol!=='https:'||!parsed.hostname.endsWith('.supabase.co')||!publishableKey.startsWith('sb_publishable_'))throw Error('Desktop cloud configuration is invalid.');
const env={...process.env,FOCUSBASE_DESKTOP:'1',NEXT_PUBLIC_CLOUD_AUTH_ENABLED:'true',NEXT_PUBLIC_SITE_URL:'focusbase://app/'};
const result=spawnSync(process.execPath,[path.join(root,'node_modules/next/dist/bin/next'),'build'],{cwd:root,env,stdio:'inherit'});
if(result.status!==0)process.exit(result.status||1);
await require('sharp')(path.join(root,'public/favicon.svg')).resize(256,256).png().toFile(path.join(root,'desktop/icon.png'));
console.log('Desktop site and icon ready.');
